### ISSUE TITLE
Skylar's Public Roadmap

### ISSUE THREAD

**Issue by ElasticBottle** [curdinc/skylar-email#58]
Below are a long list of things that we are aware of and working on. 

Feel free to [open an issue](https://github.com/curdinc/skylar-email/issues/new/choose) if you notice anything else outside this list!

Note that items are sorted in no particular order.

- [x] #62
- [x] fix: redirect from `/id` where `id ≠ 1` redirect to `1` but takes a long delay to redirect to onboarding if there are no providers.
- [x] #72
- [x] #77
- [x] chore: Add event recording/logging for user errors
- [x] #79
- [x] #76
- [x] #75
- [x] #73
- [x] #74
- [x] #78
- [ ] #81
    - [ ] feat: Displaying in message thread
    - [ ]  feat: Ensure attachments are only laded when the user is just about to view attachment(say hover on the thread preview or smthng)
    - [ ] perf: speed up attachment fetching with batch request (to be measured)
- [ ] #84
- [ ] feat: searching of messages
- [ ] feat: support mobile views
- [ ] feat: add ability to multi select email and bulk edit them
- [ ] fix: replies not threading properly
- [ ] fix: replace archive with marking as done (remove all labels, add `skylar_done`)
- [ ] feat: Autocomplete contacts
- [ ] chore: Toast component is feeling a little lackluster right now. Replace with https://sonner.emilkowal.ski/
- [ ] fix: attachment preview image is not showing up in gmail
- [ ] fix: some jank around attachment sizes near the 25 mb size limit
- [ ] perf: sending mail should update the thread that the user is replying too almost instantly
- [ ] feat: composing a reply to save state to draft every so often
- [ ] chore: email viewing is still not great
- [ ] chore: Add error toast when failing actions on toolkit
- [ ] refactor: consider using postal-mime to parse incoming gmail messages [[npm: postal-mime](https://www.npmjs.com/package/postal-mime)](https://www.npmjs.com/package/postal-mime)
- [ ] chore: clean up toolbar for compose screen
- [ ] feat: port [email reply parser](https://www.npmjs.com/package/email-forward-parser and https://www.npmjs.com/package/email-reply-parser?activeTab=readme) to get it working on the client side and use it to parse incoming replies and forwarded messages
- [ ] feat: sort the email provider order and have it persists
- [ ] feat: should have context menu for labels with common actions (rename, delete etc).
- [ ] feat: Should be able to multi select emails and do actions on them
- [ ] feat: add a way to force inbox refresh if the user wants too check for new mail
- [ ] feat: `from` should be a dropdown selection between all the different linked email providers  - why???
- [ ] feat: integrate amp-type https://amp.dev/documentation/guides-and-tutorials/integrate/add-email
- [ ] fix: changing mailbox via shortcut doesn’t work on Mac
- [ ] feat: support outlook
- [ ] research: look into supporting IMAP and SMTP

**Comment by isaachinman** [comment]
Hey @ElasticBottle – are you still working on this project?

**Comment by ElasticBottle** [comment]
Hey @isaachinman we are not actively working on this right now but hope to pick it back up at some point in the future!
